#!/env/python
# Usage: nosetests test.py

from classicalcrypto import *

class TestCaeser:
  plain      = "HELLOWORLD"
  expected   = "URYYBJBEYQ"
  shifts     = {0: 'HELLO', 1: 'IFMMP', 2: 'JGNNQ', 3: 'KHOOR', 4: 'LIPPS', 5: 'MJQQT', 6: 'NKRRU', 7: 'OLSSV', 8: 'PMTTW', 9: 'QNUUX', 10: 'ROVVY', 
                11: 'SPWWZ', 12: 'TQXXA', 13: 'URYYB', 14: 'VSZZC', 15: 'WTAAD', 16: 'XUBBE', 17: 'YVCCF', 18: 'ZWDDG', 19: 'AXEEH', 20: 'BYFFI', 
                21: 'CZGGJ', 22: 'DAHHK', 23: 'EBIIL', 24: 'FCJJM', 25: 'GDKKN', 26: 'HELLO'}

  def test_caeser_rot13(self):    
    assert caeser(self.plain, 13)    == self.expected
    assert caeser(self.expected, 13) == self.plain

  def test_caeser_various_shifts(self):
    for i in range(-30, 30):
        assert caeser(self.shifts[0], i) == self.shifts[i % 26]

  def test_caeser_brute(self):
    assert caeser(self.shifts[0]) == self.shifts


class TestOTP:
    ciphertext = "XTEZPTPRPBFGTBOJPKYEAAZPXOBFTYAPWMERMMSDBFJGQUGBAMHNWSEKTSPVIVFAXFJ"
    plaintext  = "EMAILTHEWORDTOIFYOUCANTBEANATHELETEATLOSTBOYDOTNETANDWAITFORMORETFS"
    key        = "THEREAINTNODANGERWECANGOTOOFARWESTARTBELIEVINGNOWTHATWECANBEWHOWEAREGREASEISTHEWORDTHEYTHINKOURLOVEISJUSTAGROWINGPAIN"
    key_inside = """ISOLVEMYPROBLEMSANDISEETHELIGHTWEGOTTAPLUGANDTHINKWEGOTTAFEEDITRIGHTTHEREAINTNODANGERWECANGOTOFARWESTARTBELIEVINGNOWTHATWECANBEWHOWEARE
        GREASEISTHEWORDTHEYTHINKOURLOVEISJUSTAGROWINGPAINWHYDONTTHEYUNDERSTANDITSJUSTACRYINGSHAMETHEIRLIPSARELYINGONLYREALISREALWESTARTTOFINDRIGHTNOWWEGOTTOBEW
        HATWEFEELGREASEISTHEWORDGREASEISTHEWORDISTHEWORDTHATYOUHEARDITSGOTGROOVEITSGOTMEANINGGREASEISTHETIMEISTHEPLACEISTHEMOTIONGREASEISTHEWAYWEAREFEELINGWETA
        KETHEPRESSUREANDWETHROWAWAYCONVENTIONALITYBELONGSTOYESTERDAYTHEREISACHANCETHATWECANMAKEITSOFARWESTARTBELIEVINGNOWTHATWECANBEWOWEAREGREASEISTHEWORDGREAS
        EISTHEWORDISTHEWORDTHATYOUHEARDITSGOTGROOVEITSGOTMEANINGGREASEISTHETIMEISTHEPLACEISTHEMOTIONGREASEISTHEWAYWEAREFEELINGTHISISTHELIFEOFILLUSIONWRAPPEDUPI
        NTROUBLELACEDWITHCONFUSIONWHATWEDOINGHEREWETAKETHEPRESSUREANDWETHROWAWAYCONVENTIONALITYBELONGSTOYESTERDAYTHEREISACHANCETHATWECANMAKEITSOFARWESTARTBELIE
        VINGNOWTHATWECANBEWHOWEAREGREASEISTHEWORDGREASEISTHEWORDISTHEWORDTHATYOUHEARDITSGOTGROOVEITSGOTMEANINGGREASEISTHETIMEISTHEPLACEISTHEMOTIONGREASEISTHEWA
        YWEAREFEELINGGREASEISTHEWORDISTHEWORDTHATYOUHEARDITSGOTGROOVEITSGOTMEANINGGREASEISTHETIMEISTHEPLACEISTHEMOTIONGREASEISTHEWAYWEAREFEELING"""
    short_vigenere_key   = "GREASE"
    
    def test_otp(self):
        assert otp_encrypt(self.plaintext, self.key) == self.ciphertext
        assert otp_decrypt(self.ciphertext, self.key) == self.plaintext